### PR TITLE
Fixed description

### PR DESCRIPTION
**Pull request by Iamtodor**
Orthography mistake

### CODE REVIEW

**Comment by Iamtodor** [comment]
I signed it!

**Comment by nageshs** [comment]
@Iamtodor Thank you for the pull request. This also need to be fixed in activity_main_done.xml which is referring to the string.

**Comment by Iamtodor** [comment]
Nope, it doesn't refer to the string until user it writes from the last lesson: https://codelabs.developers.google.com/codelabs/constraint-layout/index.html#8

**Comment by nageshs** [comment]
This was still being used in activity_main_done.xml so I've updated both the strings and made a commit https://github.com/googlecodelabs/constraint-layout/commit/bf6c5e7f3cd5c3b6a59c307b5eaed6448b89b90e. Thank you so much for bringing this to my attention.

**Pull request closed without merging**
